## Outline:
* [Numpy](#numpy)
* [Pandas](#pandas)
* [Statistics](#statistics)

In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib
import matplotlib.pyplot as plt

%precision 2

csvpath = 'https://covid.ourworldindata.org/data/owid-covid-data.csv'

## Numpy <a class="anchor" id="numpy"></a>

In [2]:
ar1 = np.arange(1, 11, 2)
ar2 = np.array(list(range(1, 11, 2)))
print('np.arange(1, 11, 2):', ar1)
print('np.array(list(range(1, 11, 2))):', ar2)
print('ar1 == ar2:', ar1 == ar2)
print('np.array_equal(ar1, ar2):', np.array_equal(ar1, ar2))
print()
ar3 = np.arange(1, 11).reshape(2,5)
print('np.arange(1, 11).reshape(2,5):\n', ar3)
print()
print('multi-dimentional:')
ar4 = np.arange(1,9).reshape(2,2,2)
print(ar4)
print()
print('np.linspace:')
ar5 = np.linspace(0, 1, 11)
print(ar5)
print('\nnp.diag')
ar6 = np.diag([1,2,3])
print(ar6)
print('\nnp.repeat')
print(np.array([1,2,3]*3))
print(np.repeat([1,2,3], 3))
print()
print('np.vstack([ar1, ar1**2]):\n', np.vstack([ar1, ar1**2]))
print()
print('np.hstack([ar1, ar1**2]):\n', np.hstack([ar1, ar1**2]))

np.arange(1, 11, 2): [1 3 5 7 9]
np.array(list(range(1, 11, 2))): [1 3 5 7 9]
ar1 == ar2: [ True  True  True  True  True]
np.array_equal(ar1, ar2): True

np.arange(1, 11).reshape(2,5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

multi-dimentional:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.linspace:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

np.diag
[[1 0 0]
 [0 2 0]
 [0 0 3]]

np.repeat
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]

np.vstack([ar1, ar1**2]):
 [[ 1  3  5  7  9]
 [ 1  9 25 49 81]]

np.hstack([ar1, ar1**2]):
 [ 1  3  5  7  9  1  9 25 49 81]


In [3]:
ar = np.arange(10)
print(ar.reshape(2,5))
print()
print(ar)
print()
print(ar.resize(2,5))
print()
print(ar)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9]

None

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
a = np.arange(1, 4)
print('a:', a)
print('np.dot(a,a):', np.dot(a, a))
print('a.dot(a):', a.dot(a))
print('a.dot(a.T):', a.dot(a.T))
print('*'*10)
ar = np.arange(1, 7).reshape(2,3)
print('ar:\n', ar)
print('ar.dot(ar.T):\n', ar.dot(ar.T))
print('np.dot(ar,ar.T):\n', np.dot(ar,ar.T))
print('np.inner(ar, ar):\n', np.inner(ar, ar))
print('np.outer(ar, ar):\n', np.outer(ar, ar))

a: [1 2 3]
np.dot(a,a): 14
a.dot(a): 14
a.dot(a.T): 14
**********
ar:
 [[1 2 3]
 [4 5 6]]
ar.dot(ar.T):
 [[14 32]
 [32 77]]
np.dot(ar,ar.T):
 [[14 32]
 [32 77]]
np.inner(ar, ar):
 [[14 32]
 [32 77]]
np.outer(ar, ar):
 [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [5]:
ar = np.arange(1, 28)
ar.resize(3,3,3)
arorigin = ar.copy()
ar[-2:, -2:, -2:] = 0
print(ar)
print(), print(), print()
print(arorigin)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13  0  0]
  [16  0  0]]

 [[19 20 21]
  [22  0  0]
  [25  0  0]]]



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [6]:
randar = np.random.randint(1, 10, (300,400)) #not inclusive
print(np.sum(randar==1))
print(np.sum(randar==10))
randar

13514
0


array([[9, 8, 4, ..., 6, 3, 1],
       [9, 2, 8, ..., 4, 7, 3],
       [1, 6, 7, ..., 4, 1, 5],
       ...,
       [2, 4, 1, ..., 9, 5, 5],
       [6, 2, 8, ..., 1, 6, 6],
       [8, 8, 1, ..., 9, 5, 5]])

In [7]:
ar = np.arange(4).reshape(2,2)
for i,j in zip(ar, ar):
    print(i)
    print(j)
    print()
    
ar = np.arange(8).reshape((2,2,2))
for i,j in zip(ar, ar):
    print(i)
    print(j)
    print()

[0 1]
[0 1]

[2 3]
[2 3]

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]

[[4 5]
 [6 7]]
[[4 5]
 [6 7]]



## Pandas <a class="anchor" id="pandas"></a>

### Series

In [8]:
ser1 = pd.Series([10,20,30], index= ['A', 'B', 'C'], name='Serie 1')
print(ser1)
print()
ser2 = pd.Series({'A':10, 'B':20, 'C':30}, name='Serie 2')
print(ser2)
print()
print(ser1 == ser2)
print()
print(pd.Series.equals(ser1, ser2))

A    10
B    20
C    30
Name: Serie 1, dtype: int64

A    10
B    20
C    30
Name: Serie 2, dtype: int64

A    True
B    True
C    True
dtype: bool

True


In [9]:
ser1 = pd.Series(data= {'A':10, 'B':20, 'C':None})
print(ser1)
print()
print('index: ', ser1.index)
print()
print('values: ', ser1.values)
print()
print(ser1.dtype)
print(len(ser1), ser1.shape)
print()
print(ser1[0], ser1['B'], ser1['C'])
print(ser1.iloc[0], ser1.iloc[1], ser1.iloc[2])
print(ser1.loc['A'], ser1.loc['B'], ser1.loc['C'])
print()
print(ser1.describe())

A    10.0
B    20.0
C     NaN
dtype: float64

index:  Index(['A', 'B', 'C'], dtype='object')

values:  [10. 20. nan]

float64
3 (3,)

10.0 20.0 nan
10.0 20.0 nan
10.0 20.0 nan

count     2.000000
mean     15.000000
std       7.071068
min      10.000000
25%      12.500000
50%      15.000000
75%      17.500000
max      20.000000
dtype: float64


In [10]:
s = pd.Series([10, 20, 30.001, None])
s1 = s.copy()
s2 = s.copy()
s3 = s1.append(s2)
print('s3:')
print(s3)
print()
print('s3.iloc[0]: ', s3.iloc[0])
print('s3.loc[0]:')
print(s3.loc[0])
print()
print('s3[0]')
print(s3[0])
print()
print('mathematical operations:')
print('s1 * s2')
print(s1 * s2)
print()
print('s1 / s2')
print(s1 / s2)
print()
print('s1 + s2')
print(s1 + s2)

s3:
0    10.000
1    20.000
2    30.001
3       NaN
0    10.000
1    20.000
2    30.001
3       NaN
dtype: float64

s3.iloc[0]:  10.0
s3.loc[0]:
0    10.0
0    10.0
dtype: float64

s3[0]
0    10.0
0    10.0
dtype: float64

mathematical operations:
s1 * s2
0    100.000000
1    400.000000
2    900.060001
3           NaN
dtype: float64

s1 / s2
0    1.0
1    1.0
2    1.0
3    NaN
dtype: float64

s1 + s2
0    20.000
1    40.000
2    60.002
3       NaN
dtype: float64


In [11]:
s = pd.Series(range(10, 13))
s += 1
print(s)
print()
s[3] = None
print(s)
print()
print('s[3] == None: ', s[3] == None)
print()
print('s[3] == np.nan: ', s[3] == np.nan)
print('s[3] is np.nan: ', s[3] is np.nan)
print('np.nan == np.nan: ', np.nan == np.nan)
print('np.isnan(np.nan): ', np.isnan(np.nan))
print('pd.isna(s[3]):', pd.isna(s[3]))
print('pd.isna(s):\n', pd.isna(s))

0    11
1    12
2    13
dtype: int64

0      11
1      12
2      13
3    None
dtype: object

s[3] == None:  True

s[3] == np.nan:  False
s[3] is np.nan:  False
np.nan == np.nan:  False
np.isnan(np.nan):  True
pd.isna(s[3]): True
pd.isna(s):
 0    False
1    False
2    False
3     True
dtype: bool


### DataFrames

In [12]:
ser1 = pd.Series({'A':1, 'B':2, 'C':3})
ser2 = pd.Series({'A':4, 'B':5, 'C':6, 'D':None})
ser3 = pd.Series({'A':7, 'B':8, 'C':9, 'E': 10.0})
pd.DataFrame([ser1, ser2, ser3], index=['Serie 1', 'Serie 2', 'Serie 3'])

A    B    C   D     E
Serie 1  1.0  2.0  3.0 NaN   NaN
Serie 2  4.0  5.0  6.0 NaN   NaN
Serie 3  7.0  8.0  9.0 NaN  10.0

In [13]:
dfalldata = pd.read_csv(csvpath)
dforigin = pd.read_csv(csvpath, usecols=['location', 'date', 'new_cases', 'new_deaths', 'new_tests', 
                                         'population', 'population_density', 'hospital_beds_per_100k'])
print(dforigin.head(2))
print()
print(dforigin.tail(2))
print()
print(dforigin.describe())

  location        date  new_cases  new_deaths  new_tests  population  \
0    Aruba  2020-03-13          2           0        NaN    106766.0   
1    Aruba  2020-03-20          2           0        NaN    106766.0   

   population_density  hospital_beds_per_100k  
0               584.8                     NaN  
1               584.8                     NaN  

            location        date  new_cases  new_deaths  new_tests  \
20344  International  2020-03-02          0           0        NaN   
20345  International  2020-03-10         -9           1        NaN   

       population  population_density  hospital_beds_per_100k  
20344         NaN                 NaN                     NaN  
20345         NaN                 NaN                     NaN  

           new_cases    new_deaths      new_tests    population  \
count   20346.000000  20346.000000    4912.000000  2.028200e+04   
mean      556.041974     34.931190   10657.827565  1.077231e+08   
std      4955.958003    332.73506

In [14]:
df = dforigin.copy()
print(len(df), df.shape)
print('df index: ', df.index)
print('df columns: ', df.columns)
print()
df.set_index('date', inplace=True)
df.sort_index(inplace=True)
print('df index: ', df.index)
print()
print(df.head(2))

20346 (20346, 8)
df index:  RangeIndex(start=0, stop=20346, step=1)
df columns:  Index(['location', 'date', 'new_cases', 'new_deaths', 'new_tests',
       'population', 'population_density', 'hospital_beds_per_100k'],
      dtype='object')

df index:  Index(['2019-12-31', '2019-12-31', '2019-12-31', '2019-12-31', '2019-12-31',
       '2019-12-31', '2019-12-31', '2019-12-31', '2019-12-31', '2019-12-31',
       ...
       '2020-05-28', '2020-05-28', '2020-05-28', '2020-05-28', '2020-05-28',
       '2020-05-28', '2020-05-28', '2020-05-28', '2020-05-28', '2020-05-28'],
      dtype='object', name='date', length=20346)

           location  new_cases  new_deaths  new_tests  population  \
date                                                                
2019-12-31  Algeria          0           0        NaN  43851043.0   
2019-12-31     Iraq          0           0        NaN  40222503.0   

            population_density  hospital_beds_per_100k  
date                                        

In [15]:
# Multi-level index
df = (dforigin[['location', 'date', 'new_cases', 'new_deaths', 'new_tests']]
      .copy()
      .set_index(['location', 'date'])
      .sort_index())
print(df.head(3))
print()

# df['location'] and df[['location', 'date']] --> KeyError
print('df.index.nlevels:', df.index.nlevels)
print('df.index.names:', df.index.names)
print(df.index[:2])
print(df.index.levels[1][:2])
print()
print(df.loc[('Austria', '2020-01-01'):('Austria', '2020-01-03'), ['new_cases', 'new_deaths']])
print(), print()
print(df.loc[('Afghanistan', '2020-01-01'):('Armenia', '2020-01-01'), ['new_cases', 'new_deaths']])
print()

                        new_cases  new_deaths  new_tests
location    date                                        
Afghanistan 2019-12-31          0           0        NaN
            2020-01-01          0           0        NaN
            2020-01-02          0           0        NaN

df.index.nlevels: 2
df.index.names: ['location', 'date']
MultiIndex([('Afghanistan', '2019-12-31'),
            ('Afghanistan', '2020-01-01')],
           names=['location', 'date'])
Index(['2019-12-31', '2020-01-01'], dtype='object', name='date')

                     new_cases  new_deaths
location date                             
Austria  2020-01-01          0           0
         2020-01-02          0           0
         2020-01-03          0           0


                        new_cases  new_deaths
location    date                             
Afghanistan 2020-01-01          0           0
            2020-01-02          0           0
            2020-01-03          0           0
            2020-0

In [16]:
df = dforigin.copy()
df.loc[100000] = None
print('df.loc[100000] = None\n', df.tail(3))
print()
print('df.isna().sum().sum(): ', df.isna().sum().sum())
print()
df.fillna('$$$', inplace=True)
df[100000] = None
print('df[100000] = None !new column is added with title 100000! \n', df.tail(3))
print()
print('df.isna().sum().sum(): ', df.isna().sum().sum())

df.loc[100000] = None
              location        date  new_cases  new_deaths  new_tests  \
20344   International  2020-03-02        0.0         0.0        NaN   
20345   International  2020-03-10       -9.0         1.0        NaN   
100000            NaN         NaN        NaN         NaN        NaN   

        population  population_density  hospital_beds_per_100k  
20344          NaN                 NaN                     NaN  
20345          NaN                 NaN                     NaN  
100000         NaN                 NaN                     NaN  

df.isna().sum().sum():  19751

df[100000] = None !new column is added with title 100000! 
              location        date new_cases new_deaths new_tests population  \
20344   International  2020-03-02         0          0       $$$        $$$   
20345   International  2020-03-10        -9          1       $$$        $$$   
100000            $$$         $$$       $$$        $$$       $$$        $$$   

       population_densi

#### Group by

In [17]:
df = dforigin.copy().set_index('date').sort_index()
group, frame = next(iter(df.groupby('location')))
print(group)
print('type(frame): ', type(frame))
print(frame.head(2))

Afghanistan
type(frame):  <class 'pandas.core.frame.DataFrame'>
               location  new_cases  new_deaths  new_tests  population  \
date                                                                    
2019-12-31  Afghanistan          0           0        NaN  38928341.0   
2020-01-01  Afghanistan          0           0        NaN  38928341.0   

            population_density  hospital_beds_per_100k  
date                                                    
2019-12-31              54.422                     0.5  
2020-01-01              54.422                     0.5  


In [18]:
df = dforigin.copy()
print(df.groupby('location').agg({'new_cases': [np.sum, np.max], 'new_deaths': np.average, 'new_tests': np.sum}).head(3))

            new_cases       new_deaths new_tests
                  sum  amax    average       sum
location                                        
Afghanistan     12456  1063   1.621429       0.0
Albania          1050    34   0.407407       0.0
Algeria          8857   199   4.296552       0.0


In [19]:
df = dforigin.copy().set_index(['location', 'date']).sort_index()
print(df.groupby(level=0)['new_cases', 'new_deaths', 'new_tests'].agg([np.sum,np.max]).head(2))
print()
print(df.groupby(level=1)['new_cases', 'new_deaths', 'new_tests'].agg({'sum': np.sum, 'max': np.max}).tail(2))

            new_cases       new_deaths      new_tests     
                  sum  amax        sum amax       sum amax
location                                                  
Afghanistan     12456  1063        227   32       0.0  NaN
Albania          1050    34         33    3       0.0  NaN

                 sum                             max                     
           new_cases new_deaths  new_tests new_cases new_deaths new_tests
date                                                                     
2020-05-27    191752       7872  1123479.0     95876       3936  285440.0
2020-05-28    200970      10284   770933.0    100485       5142  285288.0


C:\Users\Abtin\Miniconda2\envs\py36\lib\site-packages\pandas\core\groupby\generic.py:1455: FutureWarning: using a dict with renaming is deprecated and will be removed
in a future version.

For column-specific groupby renaming, use named aggregation

    >>> df.groupby(...).agg(name=('column', aggfunc))

  return super().aggregate(arg, *args, **kwargs)


#### Pivot tables

In [20]:
df = dforigin.copy()
df.pivot_table(values= 'new_cases', index='date', columns= 'location', aggfunc=np.sum).sort_index()

location    Afghanistan  Albania  Algeria  Andorra  Angola  Anguilla  \
date                                                                   
2019-12-31          0.0      NaN      0.0      NaN     NaN       NaN   
2020-01-01          0.0      NaN      0.0      NaN     NaN       NaN   
2020-01-02          0.0      NaN      0.0      NaN     NaN       NaN   
2020-01-03          0.0      NaN      0.0      NaN     NaN       NaN   
2020-01-04          0.0      NaN      0.0      NaN     NaN       NaN   
...                 ...      ...      ...      ...     ...       ...   
2020-05-24        782.0      8.0    195.0      0.0     0.0       0.0   
2020-05-25        584.0      9.0    193.0      1.0     9.0       0.0   
2020-05-26        591.0      6.0    197.0      0.0     0.0       0.0   
2020-05-27        658.0     25.0    194.0      0.0     2.0       0.0   
2020-05-28        625.0     21.0    160.0      0.0     0.0       0.0   

location    Antigua and Barbuda  Argentina  Armenia  Aruba  ...  Uruguay  \
date                                                        ...            
2019-12-31                  NaN        NaN      0.0    NaN  ...      NaN   
2020-01-01                  NaN        NaN      0.0    NaN  ...      NaN   
2020-01-02                  NaN        NaN      0.0    NaN  ...      NaN   
2020-01-03                  NaN        NaN      0.0    NaN  ...      NaN   
2020-01-04                  NaN        NaN      0.0    NaN  ...      NaN   
...                         ...        ...      ...    ...  ...      ...   
2020-05-24                  0.0      704.0    374.0    0.0  ...     11.0   
2020-05-25                  0.0      723.0    359.0    0.0  ...      5.0   
2020-05-26                  0.0      552.0    452.0    0.0  ...     18.0   
2020-05-27                  0.0      600.0    289.0    0.0  ...      2.0   
2020-05-28                  0.0      705.0    372.0    0.0  ...     14.0   

location    Uzbekistan  Vatican  Venezuela  Vietnam  Western Sahara     World  \
date                                                                            
2019-12-31         NaN      NaN        NaN      0.0             NaN      27.0   
2020-01-01         NaN      NaN        NaN      0.0             NaN       0.0   
2020-01-02         NaN      NaN        NaN      0.0             NaN       0.0   
2020-01-03         NaN      NaN        NaN      0.0             NaN      17.0   
2020-01-04         NaN      NaN        NaN      0.0             NaN       0.0   
...                ...      ...        ...      ...             ...       ...   
2020-05-24        54.0      0.0        0.0      0.0             0.0  101106.0   
2020-05-25        32.0      0.0      177.0      1.0             0.0   94216.0   
2020-05-26        97.0      0.0       56.0      1.0             0.0   89096.0   
2020-05-27        72.0      0.0       34.0      1.0             0.0   95876.0   
2020-05-28         0.0      0.0       34.0      0.0             0.0  100485.0   

location    Yemen  Zambia  Zimbabwe  
date                                 
2019-12-31    NaN     NaN       NaN  
2020-01-01    NaN     NaN       NaN  
2020-01-02    NaN     NaN       NaN  
2020-01-03    NaN     NaN       NaN  
2020-01-04    NaN     NaN       NaN  
...           ...     ...       ...  
2020-05-24    7.0     0.0       0.0  
2020-05-25   10.0     0.0       0.0  
2020-05-26   15.0     0.0       0.0  
2020-05-27   12.0     0.0       0.0  
2020-05-28    6.0   137.0      76.0  

[150 rows x 212 columns]

#### Date and time

In [21]:
print(pd.Timestamp('9/1/2016 10:05AM'))
print(pd.Period('1/2016'))
print(pd.to_datetime('4.7.12', dayfirst=True))
print(pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016'))
print(pd.Timestamp('9/2/2016 8:10AM') + pd.Timedelta('12D 3H'))

2016-09-01 10:05:00
2016-01
2012-07-04 00:00:00
2 days 00:00:00
2016-09-14 11:10:00


In [22]:
df = dforigin.copy().set_index('date').sort_index()
df.index = pd.to_datetime(df.index)
print(df.index.weekday_name)
print()
df['2020-05-01':'2020-05-03']

Index(['Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday',
       'Tuesday', 'Tuesday', 'Tuesday', 'Tuesday',
       ...
       'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday', 'Thursday',
       'Thursday', 'Thursday', 'Thursday', 'Thursday'],
      dtype='object', name='date', length=20346)



location  new_cases  new_deaths  new_tests  \
date                                                                         
2020-05-01                         Kenya         12           2     1434.0   
2020-05-01                    Azerbaijan         38           1        NaN   
2020-05-01                       Vietnam          0           0        NaN   
2020-05-01  Democratic Republic of Congo         72           0        NaN   
2020-05-01                      Botswana          0           0        NaN   
...                                  ...        ...         ...        ...   
2020-05-03                   Afghanistan        134           4        NaN   
2020-05-03                    Luxembourg         10           0      658.0   
2020-05-03                 Cote d'Ivoire         29           0        NaN   
2020-05-03                       Austria         12           7     4736.0   
2020-05-03                  South Africa        385           7    15061.0   

            population  population_density  hospital_beds_per_100k  
date                                                                
2020-05-01  53771300.0              87.324                    1.40  
2020-05-01  10139175.0             119.309                    4.70  
2020-05-01  97338583.0             308.127                    2.60  
2020-05-01  89561404.0              35.879                     NaN  
2020-05-01   2351625.0               4.044                    1.80  
...                ...                 ...                     ...  
2020-05-03  38928341.0              54.422                    0.50  
2020-05-03    625976.0             231.447                    4.51  
2020-05-03  26378275.0              76.399                     NaN  
2020-05-03   9006400.0             106.749                    7.37  
2020-05-03  59308690.0              46.754                    2.32  

[629 rows x 7 columns]

## Statistics <a class="anchor" id="statistics"></a>

In [23]:
print('binomial: ', np.random.binomial(1, 0.9, 10))
print('uniform : ', np.random.uniform(0, 5, 10))
print('normal  : ', np.random.normal(0, 1, 10))

binomial:  [1 1 1 1 1 1 1 1 1 1]
uniform :  [0.18 3.15 3.47 0.04 2.52 1.45 0.01 0.96 0.46 1.71]
normal  :  [-0.43 -1.09 -0.97 -1.14  0.66  0.34  0.7  -0.54 -0.49 -0.69]


**stats.ttest_ind?**

Calculate the T-test for the means of *two independent* samples of scores.

This is a two-sided test for the null hypothesis that 2 independent samples
have identical average (expected) values. This test assumes that the
populations have identical variances by default.

**Hypothesis: Italy and Spain have reported different death-rates?**

In [24]:
# calculating the average increase rate in new_deaths for each country
alpha = 0.05
country1, country2 = 'Italy', 'Spain'
df = (dfalldata[['location', 'date', 'new_cases', 'new_deaths']]
      .copy())
df['date'] = pd.to_datetime(df['date'])
df = df.set_index(['location', 'date']).sort_index()
print(df.head(3))
print()
c1df = df.loc[country1]
print('country1df:', c1df.head(3))
print()
c2df = df.loc[country2]
print('country2df:', c2df.head(3))
print()
c1initdate = c1df.loc[c1df['new_cases'] > 0, 'new_cases'].idxmin()
c1df = c1df.loc[c1initdate:]
c2initdate = c2df.loc[c2df['new_cases'] > 0, 'new_cases'].idxmin()
c2df = c2df.loc[c2initdate:]
# find the date the first death reported and drop all records before that for that country
c1df['death_ratio'] = (c1df['new_deaths'] / c1df['new_cases']).fillna(0)
c2df['death_ratio'] = (c2df['new_deaths'] / c2df['new_cases']).fillna(0)
res = stats.ttest_ind(c1df['death_ratio'], c2df['death_ratio'])
if res.pvalue < alpha:
    print(f'pvalue < {alpha} -> It is likely that {country1} and {country2} have reported different death-rates')
else:
    print(f'pvalue > {alpha} -> It is unlikely that {country1} and {country2} have reported different death-rates')

                        new_cases  new_deaths
location    date                             
Afghanistan 2019-12-31          0           0
            2020-01-01          0           0
            2020-01-02          0           0

country1df:             new_cases  new_deaths
date                             
2019-12-31          0           0
2020-01-01          0           0
2020-01-02          0           0

country2df:             new_cases  new_deaths
date                             
2019-12-31          0           0
2020-01-01          0           0
2020-01-02          0           0

pvalue > 0.05 -> It is unlikely that Italy and Spain have reported different death-rates
