In [1]:
import numpy as np
import pandas as pd

%precision 2

csvpath = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv'

## Numpy

In [2]:
ar1 = np.arange(1, 11, 2)
ar2 = np.array(list(range(1, 11, 2)))
print('np.arange(1, 11, 2):', ar1)
print('np.array(list(range(1, 11, 2))):', ar2)
print('ar1 == ar2:', ar1 == ar2)
print('np.array_equal(ar1, ar2):', np.array_equal(ar1, ar2))
print()
ar3 = np.arange(1, 11).reshape(2,5)
print('np.arange(1, 11).reshape(2,5):\n', ar3)
print()
print('multi-dimentional:')
ar4 = np.arange(1,9).reshape(2,2,2)
print(ar4)
print()
print('np.linspace:')
ar5 = np.linspace(0, 1, 11)
print(ar5)
print('\nnp.diag')
ar6 = np.diag([1,2,3])
print(ar6)
print('\nnp.repeat')
print(np.array([1,2,3]*3))
print(np.repeat([1,2,3], 3))
print()
print('np.vstack([ar1, ar1**2]):\n', np.vstack([ar1, ar1**2]))
print()
print('np.hstack([ar1, ar1**2]):\n', np.hstack([ar1, ar1**2]))

np.arange(1, 11, 2): [1 3 5 7 9]
np.array(list(range(1, 11, 2))): [1 3 5 7 9]
ar1 == ar2: [ True  True  True  True  True]
np.array_equal(ar1, ar2): True

np.arange(1, 11).reshape(2,5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

multi-dimentional:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.linspace:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

np.diag
[[1 0 0]
 [0 2 0]
 [0 0 3]]

np.repeat
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]

np.vstack([ar1, ar1**2]):
 [[ 1  3  5  7  9]
 [ 1  9 25 49 81]]

np.hstack([ar1, ar1**2]):
 [ 1  3  5  7  9  1  9 25 49 81]


In [3]:
ar = np.arange(10)
print(ar.reshape(2,5))
print()
print(ar)
print()
print(ar.resize(2,5))
print()
print(ar)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9]

None

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
a = np.arange(1, 4)
print('a:', a)
print('np.dot(a,a):', np.dot(a, a))
print('a.dot(a):', a.dot(a))
print('a.dot(a.T):', a.dot(a.T))
print('*'*10)
ar = np.arange(1, 7).reshape(2,3)
print('ar:\n', ar)
print('ar.dot(ar.T):\n', ar.dot(ar.T))
print('np.dot(ar,ar.T):\n', np.dot(ar,ar.T))
print('np.inner(ar, ar):\n', np.inner(ar, ar))
print('np.outer(ar, ar):\n', np.outer(ar, ar))

a: [1 2 3]
np.dot(a,a): 14
a.dot(a): 14
a.dot(a.T): 14
**********
ar:
 [[1 2 3]
 [4 5 6]]
ar.dot(ar.T):
 [[14 32]
 [32 77]]
np.dot(ar,ar.T):
 [[14 32]
 [32 77]]
np.inner(ar, ar):
 [[14 32]
 [32 77]]
np.outer(ar, ar):
 [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [5]:
ar = np.arange(1, 28)
ar.resize(3,3,3)
arorigin = ar.copy()
ar[-2:, -2:, -2:] = 0
print(ar)
print(), print(), print()
print(arorigin)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13  0  0]
  [16  0  0]]

 [[19 20 21]
  [22  0  0]
  [25  0  0]]]



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [6]:
randar = np.random.randint(1, 10, (300,400)) #not inclusive
print(np.sum(randar==1))
print(np.sum(randar==10))
randar

13275
0


array([[5, 7, 9, ..., 6, 5, 4],
       [2, 8, 7, ..., 2, 5, 9],
       [6, 6, 2, ..., 5, 3, 2],
       ...,
       [5, 9, 7, ..., 4, 4, 9],
       [6, 8, 9, ..., 3, 4, 7],
       [5, 3, 7, ..., 7, 1, 5]])

In [7]:
ar = np.arange(4).reshape(2,2)
for i,j in zip(ar, ar):
    print(i)
    print(j)
    print()
    
ar = np.arange(8).reshape((2,2,2))
for i,j in zip(ar, ar):
    print(i)
    print(j)
    print()

[0 1]
[0 1]

[2 3]
[2 3]

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]

[[4 5]
 [6 7]]
[[4 5]
 [6 7]]



## Pandas

### Series

In [54]:
ser1 = pd.Series([10,20,30], index= ['A', 'B', 'C'], name='Serie 1')
print(ser1)
print()
ser2 = pd.Series({'A':10, 'B':20, 'C':30}, name='Serie 2')
print(ser2)
print()
print(ser1 == ser2)
print()
print(pd.Series.equals(ser1, ser2))

A    10
B    20
C    30
Name: Serie 1, dtype: int64

A    10
B    20
C    30
Name: Serie 2, dtype: int64

A    True
B    True
C    True
dtype: bool

True


In [80]:
ser1 = pd.Series(data= {'A':10, 'B':20, 'C':None})
print(ser1)
print()
print('index: ', ser1.index)
print()
print('values: ', ser1.values)
print()
print(ser1.dtype)
print(len(ser1), ser1.shape)
print()
print(ser1[0], ser1['B'], ser1['C'])
print(ser1.iloc[0], ser1.iloc[1], ser1.iloc[2])
print(ser1.loc['A'], ser1.loc['B'], ser1.loc['C'])
print()
print(ser1.describe())

A    10.0
B    20.0
C     NaN
dtype: float64

index:  Index(['A', 'B', 'C'], dtype='object')

values:  [10. 20. nan]

float64
3 (3,)

10.0 20.0 nan
10.0 20.0 nan
10.0 20.0 nan

count     2.000000
mean     15.000000
std       7.071068
min      10.000000
25%      12.500000
50%      15.000000
75%      17.500000
max      20.000000
dtype: float64


In [132]:
s = pd.Series([10, 20, 30.001, None])
s1 = s.copy()
s2 = s.copy()
s3 = s1.append(s2)
print('s3:')
print(s3)
print()
print('s3.iloc[0]: ', s3.iloc[0])
print('s3.loc[0]:')
print(s3.loc[0])
print()
print('s3[0]')
print(s3[0])
print()
print('mathematical operations:')
print('s1 * s2')
print(s1 * s2)
print()
print('s1 / s2')
print(s1 / s2)
print()
print('s1 + s2')
print(s1 + s2)

s3:
0    10.000
1    20.000
2    30.001
3       NaN
0    10.000
1    20.000
2    30.001
3       NaN
dtype: float64

s3.iloc[0]:  10.0
s3.loc[0]:
0    10.0
0    10.0
dtype: float64

s3[0]
0    10.0
0    10.0
dtype: float64

mathematical operations:
s1 * s2
0    100.000000
1    400.000000
2    900.060001
3           NaN
dtype: float64

s1 / s2
0    1.0
1    1.0
2    1.0
3    NaN
dtype: float64

s1 + s2
0    20.000
1    40.000
2    60.002
3       NaN
dtype: float64


In [188]:
s = pd.Series(range(10, 13))
s += 1
print(s)
print()
s[3] = None
print(s)
print()
print('s[3] == None: ', s[3] == None)
print()
print('s[3] == np.nan: ', s[3] == np.nan)
print('s[3] is np.nan: ', s[3] is np.nan)
print('np.nan == np.nan: ', np.nan == np.nan)
print('np.isnan(np.nan): ', np.isnan(np.nan))
print('pd.isna(s[3]):', pd.isna(s[3]))
print('pd.isna(s):\n', pd.isna(s))

0    11
1    12
2    13
dtype: int64

0      11
1      12
2      13
3    None
dtype: object

s[3] == None:  True

s[3] == np.nan:  False
s[3] is np.nan:  False
np.nan == np.nan:  False
np.isnan(np.nan):  True
pd.isna(s[3]): True
pd.isna(s):
 0    False
1    False
2    False
3     True
dtype: bool


### DataFrames

In [8]:
dforigin = pd.read_csv(csvpath)
print(dforigin.head())
print()
print(dforigin.tail())

         date       state  fips  cases  deaths
0  2020-01-21  Washington    53      1       0
1  2020-01-22  Washington    53      1       0
2  2020-01-23  Washington    53      1       0
3  2020-01-24    Illinois    17      1       0
4  2020-01-24  Washington    53      1       0

            date          state  fips  cases  deaths
4629  2020-05-25       Virginia    51  37727    1208
4630  2020-05-25     Washington    53  21005    1076
4631  2020-05-25  West Virginia    54   1782      73
4632  2020-05-25      Wisconsin    55  15646     514
4633  2020-05-25        Wyoming    56    843      12


In [28]:
df = dforigin.copy()
print(len(df), df.shape)
print(df.index)
print(df.columns)
print()
print(df.describe())

4634 (4634, 5)
RangeIndex(start=0, stop=4634, step=1)
Index(['date', 'state', 'fips', 'cases', 'deaths'], dtype='object')

              fips          cases        deaths
count  4634.000000    4634.000000   4634.000000
mean     31.557833   12015.623651    667.282909
std      18.448211   35142.199772   2558.967206
min       1.000000       1.000000      0.000000
25%      17.000000     108.000000      2.000000
50%      31.000000    1580.000000     43.000000
75%      46.000000    8689.500000    312.000000
max      78.000000  367625.000000  29138.000000
